server:
  port: 8221
mybatis:
  type-aliases-package: com.example.api.pojo
#  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
# spring 配置
spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://106.52.104.44:3306/DB01?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: and0001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
#  instance:
#    instance-id: springcloud-provider-dept
info:
  app.name: demo-springcloud
  company:name: blog.kuangstudy.com
hystrix:
  dashboard:
    proxy-stream-allow-list: localhost